// 集中所有 DOM 查询，避免各模块重复查找。
// type="module" 默认 defer，脚本执行时 DOM 已就绪，此处同步获取即可。
export const authorizeButton = document.getElementById('authorizeButton');
export const refreshButton = document.getElementById('refreshButton');
export const unbindButton = document.getElementById('unbindButton');
export const fallbackButton = document.getElementById('fallbackButton');
export const heroMessageEl = document.getElementById('heroMessage');
export const heroBatteryEl = document.getElementById('heroBattery');
export const statusChipEl = document.getElementById('statusChip');
export const deviceNameEl = document.getElementById('deviceName');
export const modeTextEl = document.getElementById('modeText');
export const protocolTextEl = document.getElementById('protocolText');
export const updatedAtEl = document.getElementById('updatedAt');
export const grantedCountEl = document.getElementById('grantedCount');
export const chargingTextEl = document.getElementById('chargingText');
export const startupToggle = document.getElementById('startupToggle');
export const startupValueEl = document.getElementById('startupValue');
export const startupHintEl = document.getElementById('startupHint');
export const overlayModeToggle = document.getElementById('overlayModeToggle');
export const overlayModeValueEl = document.getElementById('overlayModeValue');
export const overlayModeHintEl = document.getElementById('overlayModeHint');
export const hidPickerBackdrop = document.getElementById('hidPickerBackdrop');
export const hidPickerHintEl = document.getElementById('hidPickerHint');
export const hidPickerEmptyEl = document.getElementById('hidPickerEmpty');
export const hidPickerListEl = document.getElementById('hidPickerList');
export const hidPickerCancelButton = document.getElementById('hidPickerCancelButton');
export const hidPickerConfirmButton = document.getElementById('hidPickerConfirmButton');
export const appShellEl = document.querySelector('.app-shell');
